apiVersion: v1
kind: Service
metadata:
  name: counter-np
spec:
  type: NodePort
  ports:
    - port: 3000 
      protocol: TCP
      nodePort: 31000
  selector:  # 접근할 곳 지정
    app: counter
    tier: app

# NodePort는 CluterIP의 기능을 기본으로 포함합니다