apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
sepc:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
    labels:
      app: nginx
    sepc:
      containers:
        - name: nginx
          image: nginx:1.19.5