apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["sleep"]
      args: ["100000"]
      volumeMounts:
        - name: config-vol
          mountPath: /etc/config # 호스트 위치
  volumes:
    - name: config-vol
      configMap:
        name: my-config # 내 설정 파일 저장할 것 